### ISSUE TITLE
not working on XP

### ISSUE THREAD

**Issue by greggman** [greggman/HappyFunTimes#18]
It's not working on XP.  It gets the following error

```
C:\Documents and Settings\gregg>hft list
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.join (path.js:221:5)
    at getConfigPath (C:\Documents and Settings\gregg\Local Settings\Application
 Data\Greggman\HappyFunTimes\lib\config.js:57:15)
    at Object.<anonymous> (C:\Documents and Settings\gregg\Local Settings\Applic
ation Data\Greggman\HappyFunTimes\lib\config.js:61:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

```

**Comment by greggman** [comment]
Try this version


[HappyFunTimes-0.0.47-installer.exe.zip](https://github.com/greggman/HappyFunTimes/files/290560/HappyFunTimes-0.0.47-installer.exe.zip)

**Comment by greggman** [comment]
Actually I think adding the ipv6 support broke XP since XP is so old it doesn't support ipv6

**Comment by greggman** [comment]
Okay here's another version that should work. It worked for me in XP. Crossing my fingers it works for you

[HappyFunTimes-0.0.47-installer.exe.zip](https://github.com/greggman/HappyFunTimes/files/290935/HappyFunTimes-0.0.47-installer.exe.zip)

**Comment by greggman** [comment]
Try this one. Please tell me if it works for you

[HappyFunTimes-0.0.47-installer.exe.zip](https://github.com/greggman/HappyFunTimes/files/290956/HappyFunTimes-0.0.47-installer.exe.zip)
